[project]
authors = ["notPlancha <31565873+notPlancha@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "CanvasSync"
platforms = ["win-64"]
version = "0.1.0"

[tasks]
canvas = "python bin/canvas.py"

[dependencies]
python = ">=3.13.2,<3.14"

[pypi-dependencies]
requests = ">=2.32.3, <3"
six = ">=1.17.0, <2"
